In [2]:
import pandas as pd

## Reading Excel

In [3]:
Employees = pd.read_excel('./data/employee_managers.xlsx' , sheet_name='Employees')
Employees

  Employee_ID             Name   Department                 Role Manager_ID
0        E001     Aarav Sharma  Engineering         Data Analyst       M001
1        E002        Priya Das           HR         HR Executive       M002
2        E003        Rohan Sen      Finance    Financial Analyst       M003
3        E004       Ishita Roy    Marketing  Marketing Associate       M004
4        E005  Kabir Mukherjee  Engineering    Backend Developer       M001
5        E006      Meera Ghosh   Operations   Operations Analyst       M005
6        E007       Arjun Bose        Sales      Sales Executive       M006
7        E008        Sana Khan      Finance           Accountant       M003
8        E009        Dev Patel      Product      Product Analyst       M007
9        E010      Ananya Paul           HR            Recruiter       M002

In [4]:
Managers = pd.read_excel('./data/employee_managers.xlsx' , sheet_name='Managers')
Managers

,Manager_ID,Name,Department,Team_Size,Email
0,M001,Vikram Nair,Engineering,2,vikram.nair@example.com
1,M002,Sourav Chatterjee,HR,2,sourav.chatterjee@example.com
2,M003,Neha Kapoor,Finance,2,neha.kapoor@example.com
3,M004,Ritika Sen,Marketing,1,ritika.sen@example.com
4,M005,Aditya Verma,Operations,1,aditya.verma@example.com
5,M006,Pooja Iyer,Sales,1,pooja.iyer@example.com
6,M007,Kunal Dutta,Product,1,kunal.dutta@example.com
7,M008,Tanya Roy,Legal,0,tanya.roy@example.com
8,M009,Rahul Bose,Research,0,rahul.bose@example.com
9,M010,Simran Gupta,Customer Support,0,simran.gupta@example.com

## Reading Text File

- use same `read_csv` function to read text files.

In [8]:
q_a = pd.read_csv('./data/qa.txt', sep='\t')
q_a

,ArticleTitle,Question,Answer,DifficultyFromQuestioner,DifficultyFromAnswerer,ArticleFile
0,Abraham_Lincoln,Was Abraham Lincoln the sixteenth President of...,yes,easy,easy,S08_set3_a4
1,Abraham_Lincoln,Was Abraham Lincoln the sixteenth President of...,Yes.,easy,easy,S08_set3_a4
2,Abraham_Lincoln,Did Lincoln sign the National Banking Act of 1...,yes,easy,medium,S08_set3_a4
3,Abraham_Lincoln,Did Lincoln sign the National Banking Act of 1...,Yes.,easy,easy,S08_set3_a4
4,Abraham_Lincoln,Did his mother die of pneumonia?,no,easy,medium,S08_set3_a4
5,Abraham_Lincoln,Did his mother die of pneumonia?,No.,easy,easy,S08_set3_a4
6,Abraham_Lincoln,How many long was Lincoln's formal education?,18 months,medium,easy,S08_set3_a4
7,Abraham_Lincoln,How many long was Lincoln's formal education?,18 months.,medium,medium,S08_set3_a4
8,Abraham_Lincoln,When did Lincoln begin his political career?,1832,medium,easy,S08_set3_a4
9,Abraham_Lincoln,When did Lincoln begin his political career?,1832.,medium,medium,S08_set3_a4
10,Abraham_Lincoln,What did The Legal Tender Act of 1862 establish?,"the United States Note, the first paper curren...",medium,easy,S08_set3_a4
11,Abraham_Lincoln,What did The Legal Tender Act of 1862 establish?,"the United States Note, the first paper curren...",medium,easy,S08_set3_a4
12,Abraham_Lincoln,Who suggested Lincoln grow a beard?,11-year-old Grace Bedell,hard,medium,S08_set3_a4
13,Abraham_Lincoln,Who suggested Lincoln grow a beard?,Grace Bedell.,hard,medium,S08_set3_a4
14,Abraham_Lincoln,When did the Gettysburg address argue that Ame...,1776,hard,hard,S08_set3_a4
15,Abraham_Lincoln,When did the Gettysburg address argue that Ame...,1776.,hard,hard,S08_set3_a4
16,Abraham_Lincoln,Did Lincoln beat John C. Breckinridge in the 1...,yes,hard,medium,S08_set3_a4