In [14]:
import pandas as pd

# Woking with JSON

In [5]:
pd.read_json('./data/train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [17]:
pd.read_json('./data/students.json')

                                            students
0  {'id': 101, 'name': 'Anish', 'subjects': ['Pyt...
1  {'id': 102, 'name': 'Riya', 'subjects': ['Pyth...

In [ ]:
import json

data = json.load(open('./data/students.json'))

dict

In [18]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-10-09,1791504001,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-10-09,1791504001,0.0379
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-10-09,1791504001,0.6700
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-10-09,1791504001,0.8470
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-10-09,1791504001,3.7400
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-10-09,1791504001,2.4400
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-10-09,1791504001,0.1720
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-10-09,1791504001,0.2050
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-10-09,1791504001,0.2760
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-10-09,1791504001,0.2760

# Working with SQL

In [17]:
!pip install mysql.connector

Processing c:\users\91842\appdata\local\pip\cache\wheels\57\e4\98\5feafb5c393dd2540e44b064a6f95832990d543e5b4f53ea8f\mysql_connector-2.2.9-cp38-cp38-win_amd64.whl
Installing collected packages: mysql.connector
Successfully installed mysql.connector

In [17]:
from sqlalchemy import create_engine

In [19]:
connection_url = "postgresql://anish:2004@localhost:5433/world"

engine = create_engine(connection_url, echo=True)

In [36]:
df = pd.read_sql_query("SELECT * FROM city", engine , chunksize=20)
# print the first chunk of data
chunk1 = next(df)
chunk1.head()

2026-10-10 14:16:47,464 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-10-10 14:16:47,464 INFO sqlalchemy.engine.Engine SELECT * FROM city
2026-10-10 14:16:47,465 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-10-10 14:16:47,467 INFO sqlalchemy.engine.Engine ROLLBACK

   id            name countrycode       district  population
0   1           Kabul         AFG          Kabol     1780000
1   2        Qandahar         AFG       Qandahar      237500
2   3           Herat         AFG          Herat      186800
3   4  Mazar-e-Sharif         AFG          Balkh      127800
4   5       Amsterdam         NLD  Noord-Holland      731200

In [37]:
chunk2 = next(df)
chunk2.head()

   id            name countrycode       district  population
0  21      Amersfoort         NLD        Utrecht      126270
1  22      Maastricht         NLD        Limburg      122087
2  23       Dordrecht         NLD   Zuid-Holland      119811
3  24          Leiden         NLD   Zuid-Holland      117196
4  25  Haarlemmermeer         NLD  Noord-Holland      110722